### ISSUE TITLE
Missing libraries in `requirements.txt`

### ISSUE THREAD

**Issue by diliprk** [rnikitin/QuantGPT#2]
Hi @rnikitin ,
 I was facing some errors when scrapping the vbt pro website using `scrappy` because the following packages (`readability-lxml`, `html2text`) were not installed in my conda environment.
 ```bash
 pip install readability-lxml
 pip install html2text
 ```
 
 Could you kindly add them to the `requirements.txt` ?

**Comment by rnikitin** [comment]
This is now in the `develop` branch
