### ISSUE TITLE
Running Error by TypeError: float() argument must be a string or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by TianQingX** [rnikitin/QuantGPT#4]
![image](https://github.com/rnikitin/QuantGPT/assets/40229906/b9bfc1c3-d5f3-452f-86b1-fa2d9a752364)
It is installed and setting well, but running method seems has some problems.

**Comment by rnikitin** [comment]
It seems that indexing didn't go well.
Could you please try to delete /index folder, restart the app and attach logs here?

**Comment by TianQingX** [comment]
![image](https://github.com/rnikitin/QuantGPT/assets/40229906/398e717a-725e-4a05-b7db-8fa3bc44d4c5)
which file is /index folder? Do you mean indexing.md ?

**Comment by rnikitin** [comment]
No, in the project root, there is a folder ./index, where the system stores indexed files after parsing and embedding, by default its empty and it’s content can be safely deleted

**Comment by TianQingX** [comment]
![image](https://github.com/rnikitin/QuantGPT/assets/40229906/6799ae1b-9224-4781-ba34-36e87b81b68c)
It made me confused that there are no folder calls  " ./index " In the project I git clone from develop and main.

**Comment by rnikitin** [comment]
Let's check Scrapy.
Could you please show whats inside the `quant_scraper`?

**Comment by TianQingX** [comment]
![image](https://github.com/rnikitin/QuantGPT/assets/40229906/0a650570-1df1-4097-b676-a465e9efad29)
![image](https://github.com/rnikitin/QuantGPT/assets/40229906/6af2fd2c-22a9-4e5c-9e71-dde84e3a7e4f)
![image](https://github.com/rnikitin/QuantGPT/assets/40229906/6d3e5820-50c0-45cc-9f0b-4c4d6cdaeebb)
![image](https://github.com/rnikitin/QuantGPT/assets/40229906/c6d9f65d-74ec-4a64-a146-aa3c203a15d3)
![image](https://github.com/rnikitin/QuantGPT/assets/40229906/e5a9847c-0526-4645-83ae-cee347435bf1)

it has a folder call docs, and vbt folder which save all the md file

**Comment by rnikitin** [comment]
All documents are here and downloaded successfully.
Maybe it doesn't have enough permissions to create a folder `index`. 
Try to create that folder in the root of quantgpt and re-run the app with: `chainlit run quantgpt.py`

**Comment by TianQingX** [comment]
![image](https://github.com/rnikitin/QuantGPT/assets/40229906/35b4d497-d948-4a45-9799-44ff8f094deb)
Maybe the requirements should update as your environment, after running chainlit run quantgpt.py, I pip install langchain,openai,llama-index, but the version of llama 0.9.22 may not be the one that your environment required

**Comment by rnikitin** [comment]
Did you run `pip install -r requirements.txt` after cloning?

Also, I see, you're running python=3.9.
I developed it under python=3.10 and 3.11, but didn't test it with 3.9

Anyway, I strongly recommend creating an isolated virtual env for quantgpt with conda:
`conda create --name quantgpt python=3.10`
and rerun the setup process.

**Comment by TianQingX** [comment]
![image](https://github.com/rnikitin/QuantGPT/assets/40229906/19dce55f-85d3-4082-85e8-46e8bb4326a1)
Quit wired that there is same problem, and I create both index folder in quantgpt root folder and home folder
![image](https://github.com/rnikitin/QuantGPT/assets/40229906/fd58eb11-ab9d-400b-90dc-e53f5b3060ed)
![image](https://github.com/rnikitin/QuantGPT/assets/40229906/08e7db8c-c94b-4fc4-b061-a658682b3ce2)
I try it for env python = 3.9 and still the same, Maybe the requirement list needs update?

**Comment by rnikitin** [comment]
The error has been changed.
Now it can't find the .env file or at least it can't find the GPT_TEMPERATURE value in the .env file.
Please check that you have the correct .env file, the same to this one:
https://github.com/rnikitin/QuantGPT/blob/main/env.example

but put the correct values into the file.

**Comment by TianQingX** [comment]
![image](https://github.com/rnikitin/QuantGPT/assets/40229906/c297d7e6-06a5-4440-a263-ddd0f9bb0edd)
![image](https://github.com/rnikitin/QuantGPT/assets/40229906/82305f8c-c2ce-41b2-8c35-ad59986d8551)
I think the main reason is I should get CHAINLIT_API_KEY and CHAINLIT_AUTH_SECRET?

**Comment by rnikitin** [comment]
Hey, Happy New Year and how it's going?

Your error response saying, that you probably don't have .env file which you should create manually by copying/renaming `env.example` file into `.env` and set values properly.

Btw you can try a latest version from `main` branch, it's a bit easier to run, since chainlit cloud is not mandatory anymore.
