### ISSUE TITLE
OpenAI Token Error

### ISSUE THREAD

**Issue by ergunkocak** [rnikitin/quantgpt#9]
Hi,

I am getting:
``` 
error_code=insufficient_quota error_message='You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.' error_param=None error_type=insufficient_quota message='OpenAI API error received' stream_error=False
``` 

I created a new token and tried again first thing this morning. I have balance in my account i am tier 2. I realized there is also organization parameter in API requests : https://platform.openai.com/docs/api-reference/organization-optional . I tried both of 2 organisations in my account but same error.

I checked the code base for an organization parameter if it is read from .env file but could not see. Is it possible to add as an optional .env variable?

Do you have any suggestions to solve this issue? I tried asking support but it is AI and just returns check rate limiting bla bla. I checked myu yesterdays usage and it is just 1 cent :) 

Best

**Comment by rnikitin** [comment]
Hey, this is related to your OpenAI account, which usually means you don't have funds in your account.
There is nothing QuantGPT can do about that.
